name: CI

on:
  push:
    branches: [ main, duongquanghung-june2025 ]
  pull_request:
    branches: [ main, duongquanghung-june2025 ]

jobs:
  client:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./zigtask-client
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run lint --if-present
      - run: npm test -- --watchAll=false
      - run: npm run build

  api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./zigtask-api
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run lint --if-present
      - run: npm test -- --watchAll=false
      - run: npm run build 